import { APP_STORE_LABELS, LAUNCHPAD_LABELS } from "./launchpad.defaults";

// Spanish copy of the launchpad and the App Store, in neutral Spanish with "tú": the same shape as the English
// defaults, so a host passes `launchpadLabels(locale)` and `appStoreLabels(locale)` to `LaunchpadProvider`.
export const LAUNCHPAD_LABELS_ES = {
  stoneOS: "StoneOS",
  rail: { home: "StoneOS", allApps: "Todas las apps", pinned: "Fijadas", platforms: "Plataformas" },
  title: "Mis apps",
  myApps: "Mis apps",
  appStore: "App Store",
  prompt: "¿En qué quieres trabajar?",
  searchPlaceholder: "Aplicaciones",
  searchShortcut: "/",
  recent: "Recientes",
  pinned: "Fijadas",
  allApps: "Todas las apps",
  getMore: "Añadir más",
  folderStoneOS: "StoneOS",
  folderClose: "Cerrar",
  results: (count) => `${count} en tus apps`,
  noResults: (term) => `Ninguna app llamada «${term}» en tus apps.`,
  searchStore: (term) => `Buscar «${term}» en la App Store`,
  records: {
    searching: "Buscando dentro de tus apps…",
    failed: "No se pudo buscar dentro de tus apps",
    found: (count) => `${count} encontrados dentro de tus apps`,
  },
  empty: "Todavía no tienes apps",
  emptyHint: "Instala la primera desde la App Store. Las plataformas de StoneOS siempre están en la carpeta.",
  loadFailed: "No se pudieron cargar tus apps",
  group: {
    defaultName: "Grupo",
    nameLabel: "Nombre del grupo",
    rename: "Renombrar grupo",
    removeFromGroup: "Quitar del grupo",
    count: (count) => `${count} apps`,
  },
  menu: {
    open: "Abrir",
    newTab: "Abrir en pestaña nueva",
    pin: "Fijar en el launchpad",
    unpin: "Quitar del launchpad",
    copyLink: "Copiar enlace",
    viewInStore: "Ver en la App Store",
    linkCopied: "Enlace copiado",
    pinFailed: "No se pudo cambiar el pin",
  },
  manageDefinitions: "Definiciones",
  copyBlocked: "El navegador no dejó copiar",
  retry: "Reintentar",
};

export const APP_STORE_LABELS_ES = {
  // Da formato a precios y fechas.
  locale: "es",
  searchPlaceholder: "Buscar en la App Store",
  searchShortcut: "/",
  loadFailed: "No se pudo cargar la App Store",
  retry: "Reintentar",
  loading: "Cargando…",
  nav: {
    label: "Secciones de la App Store",
    discover: "Descubrir",
    allSuites: "Todas las suites",
    organizationApps: (organization) => `Apps de ${organization}`,
    organizationFallback: "Tu organización",
    yourSuites: "Tus suites",
    seeAllSuites: "Ver todas las suites",
    categories: "Categorías",
    backToMyApps: "Volver a Mis apps",
    collapse: "Contraer la barra lateral",
    expand: "Expandir la barra lateral",
    back: "Atrás",
  },
  build: {
    title: "Crea tu propia app",
    hint: "Publica herramientas internas para tus equipos aquí mismo, en la tienda.",
    action: "Empezar a crear",
  },
  discover: {
    featured: "Destacada",
    suggested: "Sugeridas para ti",
    suggestedNote: "Una selección destacada de la App Store.",
    browseSuites: "Explora por suite de negocio",
    seeAllSuites: (count) => (count > 1 ? `Ver las ${count} suites →` : "Ver todas las suites →"),
    title: "Descubrir",
    showing: (shown, total) => `Mostrando ${shown} de ${total} apps`,
    showMore: "Mostrar más",
    loadingMore: "Cargando más apps…",
    end: "Estas son todas las apps de la tienda.",
    empty: "Todavía no hay apps en la tienda.",
  },
  search: {
    resultsFor: (term) => `Resultados para «${term}»`,
    count: (count) => (count === 1 ? "1 app" : `${count} apps`),
    none: (term) => `Nada coincide con «${term}».`,
    noneHint: "Prueba con otra palabra o elige una categoría.",
    clear: "Borrar la búsqueda",
  },
  suites: {
    title: "Suites de negocio",
    subtitle: "Cada suite reúne las apps con las que funciona un tipo de negocio. Elige una para ver todas sus apps.",
    count: (count) => `${count} suites · primero las tuyas`,
    inUse: "En uso",
    usage: (used, total) => `${used} de ${total} en uso`,
    appsCount: (count) => (count === 1 ? "1 app" : `${count} apps`),
    empty: "Todavía no hay suites en la tienda.",
    kindTitles: {
      core: "Núcleo",
      business: "Suite de negocio",
      industry: "Edición sectorial",
    },
    kindGroups: {
      core: "Núcleo",
      business: "Suites de negocio",
      industry: "Ediciones sectoriales",
    },
  },
  suite: {
    getSuite: (price) => `Obtener la suite · ${price}`,
    getSuiteFree: "Obtener la suite",
    complete: "Ya tienes todas sus apps",
    summary: (total, yours) => `${total} apps · ${yours} ya son tuyas`,
    coverage: "Cobertura",
    missing: (count) => (count === 1 ? "Falta 1 app en Mis apps" : `Faltan ${count} apps en Mis apps`),
    alreadyInHub: (count) => `Ya en Mis apps · ${count}`,
    categoryFilter: "Categoría",
    allCategories: "Todas",
    appsYouCanAdd: "Apps que puedes añadir",
    appsInSuite: "Apps de esta suite",
    noApps: "Ninguna app coincide con este filtro.",
    notFound: "Esta suite no está en la tienda.",
  },
  category: {
    overline: "Categoría",
    suiteFilter: "Suite",
    allSuites: "Todas las suites",
    allApps: (category) => `Todas las apps de ${category}`,
    appsFor: (category, suite) => `Apps de ${category} para ${suite}`,
    empty: "Todavía no hay apps en esta categoría.",
    notFound: "Esta categoría no existe.",
  },
  organization: {
    title: (organization) => `Apps creadas por ${organization}`,
    hint: "Herramientas que tu organización publica para sus propios equipos.",
    build: "Crear una app",
    empty: "Tu organización todavía no ha creado ninguna app.",
  },
  card: {
    get: "Obtener",
    buy: (price) => `Comprar · ${price}`,
    view: "Ver",
    viewApp: (name) => `Ver ${name}`,
    open: "Abrir",
    free: "Gratis",
    line: (suite, category) => (suite ? `${suite} · ${category}` : category),
    noDescription: "Sin descripción",
    moreActions: "Más acciones",
    editInStudio: "Editar en Studio",
    delete: "Eliminar",
    deleteTitle: "Eliminar app",
    // El nombre de la app va en negrita entre las dos mitades.
    deleteConfirmBefore: "¿Eliminar ",
    deleteConfirmAfter: "? Dejará de funcionar para toda tu organización y no se puede deshacer.",
    cancel: "Cancelar",
    deleteFailed: "No se pudo eliminar la app",
  },
  detail: {
    by: "de",
    publisher: "Editor",
    verified: "Editor verificado",
    media: "Pantallas",
    about: "Acerca de",
    worksWith: "Funciona con",
    information: "Información",
    version: "Versión",
    updated: "Actualizada",
    dataAccess: "Acceso a datos",
    compliance: "Cumplimiento",
    support: "Soporte",
    supportLink: "Centro de ayuda",
    price: "Precio",
    priceNotes: {
      owned: "Creada por tu organización",
      entitled: "Ya está en tu organización",
      free: "Gratis para tu organización",
      oneTime: "Precio único para tu organización",
    },
    forDevelopers: "Para desarrolladores",
    capabilities: "Capacidades",
    routes: "Rutas",
    interface: "Interfaz",
    inputs: "Entradas",
    outputs: "Salidas",
    ports: "Puertos",
    defaultPort: "Predeterminado",
    notFound: "Esta app no está en la tienda.",
    notFoundHint: "Puede ser privada de otra organización o haber dejado de publicarse.",
  },
  acquire: {
    ableTo: "Esta app podrá",
    suiteApps: "Añade estas apps",
    installFor: "Instalar para",
    everyoneIn: (organization) => `Todas las personas de ${organization}`,
    price: "Precio",
    cancel: "Cancelar",
    confirmApp: "Añadir a Mis apps",
    confirmSuite: "Añadir la suite",
    progressApp: "Añadiendo a tus apps…",
    progressSuite: "Añadiendo las apps de la suite…",
    doneApp: "Ya está en Mis apps y quedó fijada en tu launchpad.",
    doneSuite: (count) => (count === 1 ? "Se añadió 1 app a Mis apps." : `Se añadieron ${count} apps a Mis apps.`),
    doneSuiteNothing: "Todas las apps de esta suite ya estaban en Mis apps.",
    open: (name) => `Abrir ${name}`,
    keepBrowsing: "Seguir explorando",
    failed: "No se pudo añadir",
    tryAgain: "Intentar de nuevo",
    close: "Cerrar",
  },
  notEntitled: {
    title: "Tu organización todavía no tiene esta app",
    hint: "Obtenla en la App Store para abrirla aquí.",
    action: "Obtener esta app",
  },
  access: {
    owned: "Tuya",
    entitled: "En tus apps",
    available: "Disponible",
  },
  pricingModels: {
    free: "Gratis",
    oneTime: "Precio único",
  },
  sorts: {
    featured: "Destacadas",
    name: "Nombre",
    recent: "Actualizadas hace poco",
  },
  categoryTitles: {
    ai: "IA",
    productivity: "Productividad",
    operations: "Operaciones",
    sales: "Ventas",
    finance: "Finanzas",
    communication: "Comunicación",
    analytics: "Analítica",
    support: "Soporte",
    people: "Personas",
  },
  categoryDescriptions: {
    ai: "Apps que redactan, resumen, clasifican y automatizan con IA.",
    productivity: "Documentos, notas, hojas de cálculo, calendarios y las herramientas de cada día.",
    operations: "Lo del día a día: procesos, solicitudes, inventarios y aprobaciones.",
    sales: "Embudos, clientes, cotizaciones y todo lo que cierra una venta.",
    finance: "Pagos, facturas, liquidaciones y la contabilidad.",
    communication: "Chat, correo y las conversaciones de tus equipos.",
    analytics: "Tableros, reportes y los números detrás de cada decisión.",
    support: "Tickets, casos y la atención a las personas que atiendes.",
    people: "Directorios, contratación, ausencias y todo lo de tus equipos.",
  },
  categoryFallbackDescription: "Apps agrupadas por lo que hacen, en todas las suites.",
};

const LAUNCHPAD_LABELS_BY_LOCALE = { en: LAUNCHPAD_LABELS, es: LAUNCHPAD_LABELS_ES };
const APP_STORE_LABELS_BY_LOCALE = { en: APP_STORE_LABELS, es: APP_STORE_LABELS_ES };

/** The launchpad's copy in `locale` (English when the locale is not shipped). */
export const launchpadLabels = (locale = "en") => LAUNCHPAD_LABELS_BY_LOCALE[locale] || LAUNCHPAD_LABELS;

/** The App Store's copy in `locale` (English when the locale is not shipped). */
export const appStoreLabels = (locale = "en") => APP_STORE_LABELS_BY_LOCALE[locale] || APP_STORE_LABELS;
