// Visible chrome of the storage browser. Hosts override any subset through the `labels` prop;
// dialogs and notifications keep their English copy.
export const STORAGE_BROWSER_LABELS = {
  storage: "Storage",
  trashbox: "Trashbox",
  recent: "Recent",
  sharedWithMe: "Shared with me",
  folders: "Folders",
  noFolders: "No folders yet.",
  searchHere: "Search here",
  searchTrashbox: "Search Trashbox",
  searchRecent: "Search Recent",
  searchShared: "Search Shared with me",
  upOneLevel: "Up one level",
  folderPanel: "Folder panel",
  refresh: "Refresh",
  backToFiles: "Back to files",
  trashboxTooltip: "Trashbox — deleted items",
  newFolder: "New folder",
  newStorage: "New storage",
  upload: "Upload",
  uploadFiles: "Upload files",
  openTrashbox: "Open Trashbox",
  keyboardShortcuts: "Keyboard shortcuts",
  trashEmptyTitle: "The Trashbox is empty",
  trashEmptyDescription: "Deleted items land here so you can restore them.",
  recentEmptyTitle: "Nothing recent yet",
  recentEmptyDescription: "Files you add or change show up here.",
  sharedEmptyTitle: "Nothing shared with you yet",
  sharedEmptyDescription: "Files other people share with you or your teams show up here.",
  rootsEmptyTitle: "No storages yet",
  rootsEmptyDescription: "Create the first storage to organize this organization's files.",
  folderEmptyTitle: "This folder is empty",
  folderEmptyDescription: "Drop files here or use Upload.",
  loading: "Loading…",
  itemCount: (count) => `${count} item${count === 1 ? "" : "s"}`,
  selectionHint: "· Click selects, double-click opens",
  selectedCount: (count) => `${count} selected`,
  clearSelection: "Clear selection",
  open: "Open",
  download: "Download",
  copyLink: "Copy link",
  share: "Share",
  shareEllipsis: "Share…",
  rename: "Rename",
  move: "Move",
  moveTo: "Move to…",
  delete: "Delete",
  restore: "Restore",
  putBack: "Put back",
  deleteForever: "Delete forever",
};
